version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - ../core:/var/www/core
      - ./:/var/www/html
    ports:
      - "8080:8080"

  woodlands_db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "woodlands"
      MYSQL_PASSWORD: "W00dland5"
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqlconf:/etc/mysql/conf.d/
    ports:
      - 3306:3306

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: .
    entrypoint: /usr/bin/composer
    volumes:
      - ./:./
    profiles:
      - composer

volumes:
  mysqldata: {}
  mysqlconf: {}
