version: "3"

services:
  web:
    # image: trafex/php-nginx
    # container_name: "app"
    build:
      context: .
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: "dev"
    ports:
      - "8080:8080"
